services:
  db:
    image: postgres:latest
    container_name: forum_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: forum
    ports:
      - "5432:5432"
    networks:
      - internal_network
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  internal_network:
    driver: bridge

volumes:
  db_data:
